[project]
version = "0.1.0"
name = "async"
cincludes = []
cobjects = []
pkgconfig = []
cflags = []
lflags = []

[variants]
default = []

[dependencies]
time    = "1"
buffer  = "1"
err     = "1"
slice   = "1"
