language: rust
rust:
  - stable
os:
  - linux
  - osx
  - windows
before_install:
  - |-
      case $TRAVIS_OS_NAME in
      windows)
        curl -fsSL "https://github.com/Z3Prover/z3/releases/download/z3-4.8.8/z3-4.8.8-x64-win.zip" -o "z3-4.8.8-x64-win.zip"
        7z e "z3-4.8.8-x64-win.zip" -o/c/z3_downloaded -r -y
        export "PATH=/c/z3_downloaded:$PATH"
        rm -rf /c/z3_downloaded/z3 ## this is an empty directory
        /c/z3_downloaded/z3.exe --version
        z3 --version
        ;;
      esac
script:
  - |-
    ./ci.sh

addons:
  apt:
    packages: z3
  homebrew:
    packages: z3
    update: true
