name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]

    defaults:
      run:
        shell: bash

    steps:
    - uses: actions/checkout@v2

    - name: Prepare Artifact
      run: |
        7z a artifact.zip modules/

    - name: macos
      if: matrix.os == 'macos-latest'
      run: |
        brew install z3
        ./ci.sh

    - name: ubuntu
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get install -y z3
        ./ci.sh

    - name: windows
      if: matrix.os == 'windows-latest'
      run: |
        curl -fsSL "https://github.com/Z3Prover/z3/releases/download/z3-4.8.8/z3-4.8.8-x64-win.zip" -o "z3-4.8.8-x64-win.zip"
        rm -rf /c/z3_downloaded/z3 ## this is an empty directory
        export "PATH=/c/z3_downloaded:/c/msys64/mingw64/bin/:$PATH"
        clang --version
        export "ZZ_ASAN=false"
        ./ci.sh

    - name: Upload Release Asset
      if: github.ref == 'refs/heads/master'
      env:
       FILE: ./.zip
       AWS_REGION: 'eu-west-1'
       S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
       AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
       AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
       GITHUB_OS: ${{matrix.os}}
      run: |
        mkdir -p ~/.aws
        echo "[default]" > ~/.aws/credentials
        echo "aws_access_key_id = ${AWS_ACCESS_KEY_ID}" >> ~/.aws/credentials
        echo "aws_secret_access_key = ${AWS_SECRET_ACCESS_KEY}" >> ~/.aws/credentials

        7z a artifact.zip target/release/zz*
        aws s3 cp artifact.zip s3://${S3_BUCKET}/zz-${GITHUB_SHA}-${GITHUB_OS}.zip --region ${AWS_REGION} --acl public-read
        aws s3 cp artifact.zip s3://${S3_BUCKET}/zz-latest-${GITHUB_OS}.zip --region ${AWS_REGION} --acl public-read



